"""Slop-classifier tests — pure heuristics + mocked Hermes path."""
from __future__ import annotations

from unittest.mock import patch

from claw_hermes import slop
from claw_hermes.config import HermesConfig
from claw_hermes.github import PullRequest


def _pr(**overrides) -> PullRequest:
    base = dict(
        repo="owner/repo", number=1, title="Add new feature",
        author="alice", state="OPEN", is_draft=False,
        additions=20, deletions=2, changed_files=2,
        url="https://github.com/owner/repo/pull/1", body="",
    )
    base.update(overrides)
    return PullRequest(**base)


def _no_hermes_cfg() -> HermesConfig:
    return HermesConfig(binary="definitely-not-on-path-zzz")


def test_emoji_heavy_body_triggers_signal():
    body = "Hi! " + ("🚀" * 30) + " let's ship it 🎉🎉🎉🎉🎉"
    verdict = slop.classify(_no_hermes_cfg(), _pr(body=body), diff="")
    assert "emoji_heavy_body" in verdict.signals
    assert verdict.used_hermes is False


def test_as_an_ai_phrase_triggers_signal():
    body = "As an AI, I have refactored this module to improve readability."
    verdict = slop.classify(_no_hermes_cfg(), _pr(body=body), diff="")
    assert "ai_phrase_present" in verdict.signals


def test_generated_with_phrase_triggers_signal():
    body = "Generated with Claude Code\nCo-Authored-By: Claude <noreply@anthropic.com>"
    verdict = slop.classify(_no_hermes_cfg(), _pr(body=body), diff="")
    assert "ai_phrase_present" in verdict.signals


def test_small_typo_fix_pr_labeled_human():
    pr = _pr(title="Fix typo in README", additions=1, deletions=1, changed_files=1,
             body="Fixes a typo.")
    verdict = slop.classify(_no_hermes_cfg(), pr, diff="")
    assert verdict.label == "human"
    assert verdict.signals == ()


def test_suspiciously_round_size_signal_fires_on_large_round_pr():
    pr = _pr(additions=300, deletions=0, changed_files=5)
    verdict = slop.classify(_no_hermes_cfg(), pr, diff="")
    assert "suspiciously_round_size" in verdict.signals


def test_mass_rename_diff_signal_fires_when_additions_equal_deletions():
    pr = _pr(additions=80, deletions=80, changed_files=20)
    verdict = slop.classify(_no_hermes_cfg(), pr, diff="")
    assert "mass_rename_diff" in verdict.signals


def test_hallucinated_import_in_diff_triggers_signal():
    diff = "+from json_helper import dumps\n+import requests_async\n"
    verdict = slop.classify(_no_hermes_cfg(), _pr(additions=5, deletions=0), diff)
    assert "hallucinated_import" in verdict.signals


def test_no_tests_on_large_pr_signal_fires():
    diff = "diff --git a/src/foo.py b/src/foo.py\n+def f(): pass\n"
    pr = _pr(additions=150, deletions=10, changed_files=4)
    verdict = slop.classify(_no_hermes_cfg(), pr, diff)
    assert "no_tests_on_large_pr" in verdict.signals


def test_test_changes_suppress_no_tests_signal():
    diff = (
        "diff --git a/tests/test_foo.py b/tests/test_foo.py\n"
        "+def test_x(): assert True\n"
        "diff --git a/src/foo.py b/src/foo.py\n+def f(): pass\n"
    )
    pr = _pr(additions=150, deletions=10, changed_files=4)
    verdict = slop.classify(_no_hermes_cfg(), pr, diff)
    assert "no_tests_on_large_pr" not in verdict.signals


def test_multiple_strong_signals_label_ai_slop():
    body = (
        "As an AI language model, I generated this PR.\n"
        "🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀 ship it"
    )
    diff = "+from json_helper import dumps\n"
    pr = _pr(body=body, additions=200, deletions=0, changed_files=8)
    verdict = slop.classify(_no_hermes_cfg(), pr, diff)
    assert verdict.label == "ai-slop"
    assert verdict.confidence >= 0.6
    assert "ai_phrase_present" in verdict.signals
    assert "hallucinated_import" in verdict.signals


def test_hermes_path_used_when_binary_present(tmp_path):
    cfg = HermesConfig(binary="hermes-fake")
    fake_path = str(tmp_path / "hermes-fake")
    output = (
        "LABEL: ai-slop\n"
        "CONFIDENCE: 0.82\n"
        "REASONING: Body looks autogenerated and tests are absent.\n"
    )
    with patch("claw_hermes.slop.shutil.which", return_value=fake_path), \
         patch("claw_hermes.slop.subprocess.run") as mock_run:
        mock_run.return_value = type(
            "R", (), {"returncode": 0, "stdout": output, "stderr": ""}
        )()
        verdict = slop.classify(cfg, _pr(), diff="some diff")
    assert verdict.used_hermes is True
    assert verdict.label == "ai-slop"
    assert 0.81 <= verdict.confidence <= 0.83
    assert "autogenerated" in verdict.reasoning


def test_hermes_falls_back_to_heuristic_when_output_unparseable(tmp_path):
    cfg = HermesConfig(binary="hermes-fake")
    fake_path = str(tmp_path / "hermes-fake")
    with patch("claw_hermes.slop.shutil.which", return_value=fake_path), \
         patch("claw_hermes.slop.subprocess.run") as mock_run:
        mock_run.return_value = type(
            "R", (), {"returncode": 0, "stdout": "garbage that won't parse", "stderr": ""}
        )()
        verdict = slop.classify(cfg, _pr(), diff="")
    assert verdict.used_hermes is False


def test_hermes_disabled_short_circuits_to_heuristic():
    cfg = HermesConfig(binary="hermes-fake", enabled=False)
    with patch("claw_hermes.slop.shutil.which") as mock_which:
        verdict = slop.classify(cfg, _pr(), diff="")
    mock_which.assert_not_called()
    assert verdict.used_hermes is False


def test_verdict_label_is_one_of_three():
    body = "Fixes a small bug."
    verdict = slop.classify(_no_hermes_cfg(), _pr(body=body), diff="")
    assert verdict.label in ("human", "ai-slop", "ai-assisted-legit")
