"""``claw-hermes skill`` subcommand group: lint, new, list."""
from __future__ import annotations

import json as json_lib
import sys
from pathlib import Path

import click

from claw_hermes import manifest as manifest_mod


@click.group("skill")
def skill_group() -> None:
    """Author and validate agentskills.io v1.0 manifests with the runtimes: extension."""


@skill_group.command("lint")
@click.argument("path", type=click.Path(exists=True, file_okay=True, dir_okay=True))
@click.option("--json", "as_json", is_flag=True, help="Emit machine-readable JSON.")
@click.option("--strict", is_flag=True, help="Treat warnings as errors.")
def lint_cmd(path: str, as_json: bool, strict: bool) -> None:
    """Validate a SKILL.md manifest (file or directory of skills)."""
    target = Path(path)
    if target.is_file():
        files = [target]
    else:
        files = manifest_mod.discover(target)
        if not files:
            click.echo(f"no SKILL.md found under {target}", err=True)
            sys.exit(2)

    all_issues: list[manifest_mod.LintIssue] = []
    for f in files:
        all_issues.extend(manifest_mod.lint(f))

    errors = [i for i in all_issues if i.is_error()]
    warnings = [i for i in all_issues if not i.is_error()]

    if as_json:
        click.echo(json_lib.dumps(
            {
                "files": [str(f) for f in files],
                "issues": [
                    {"level": i.level, "code": i.code, "message": i.message, "path": i.path}
                    for i in all_issues
                ],
                "errors": len(errors),
                "warnings": len(warnings),
            },
            indent=2,
        ))
    else:
        for f in files:
            file_issues = [i for i in all_issues if i.path == str(f)]
            if not file_issues:
                click.echo(f"OK  {f}")
                continue
            click.echo(f"--  {f}")
            for issue in file_issues:
                click.echo(f"  [{issue.level}] {issue.code}: {issue.message}")
        click.echo(f"\n{len(errors)} error(s), {len(warnings)} warning(s)")

    if errors:
        sys.exit(2)
    if warnings and strict:
        sys.exit(2)
    if warnings:
        sys.exit(1)
    sys.exit(0)


@skill_group.command("new")
@click.argument("name")
@click.option("--runtime", type=click.Choice(["hermes", "openclaw", "both"]), default="both")
@click.option("--description", default=None, help="Skill description (>=50 chars).")
@click.option("--author", default="Anonymous", help="Author name.")
@click.option("--license", "license_id", default="MIT", help="SPDX license identifier.")
def new_cmd(
    name: str,
    runtime: str,
    description: str | None,
    author: str,
    license_id: str,
) -> None:
    """Scaffold a new dual-runtime skill at <name>/SKILL.md."""
    target_dir = Path(name)
    skill_name = target_dir.name
    if target_dir.exists():
        click.echo(f"refusing to overwrite existing path: {target_dir}", err=True)
        sys.exit(1)

    if not description:
        description = (
            f"Scaffolded skill '{skill_name}' generated by claw-hermes skill new. "
            "Replace this description with a concrete summary of when an agent should invoke "
            "this skill, including the trigger phrases and inputs it expects."
        )

    text = _render_scaffold(
        name=skill_name,
        description=description,
        author=author,
        license_id=license_id,
        runtime=runtime,
    )

    target_dir.mkdir(parents=True, exist_ok=False)
    skill_path = target_dir / "SKILL.md"
    skill_path.write_text(text, encoding="utf-8")

    click.echo(f"scaffolded {skill_path}")
    issues = manifest_mod.lint(skill_path)
    errors = [i for i in issues if i.is_error()]
    warnings = [i for i in issues if not i.is_error()]
    if not issues:
        click.echo("lint: clean")
    else:
        for issue in issues:
            click.echo(f"  [{issue.level}] {issue.code}: {issue.message}")
        click.echo(f"lint: {len(errors)} error(s), {len(warnings)} warning(s)")
        if errors:
            sys.exit(2)


@skill_group.command("list")
@click.argument("directory", type=click.Path(exists=True, file_okay=False, dir_okay=True))
def list_cmd(directory: str) -> None:
    """Discover all */SKILL.md skills in a directory and print a one-line summary each."""
    files = manifest_mod.discover(Path(directory))
    if not files:
        click.echo(f"no SKILL.md found under {directory}", err=True)
        sys.exit(1)
    for f in files:
        try:
            m = manifest_mod.Manifest.parse(f)
            runtimes_str = ",".join(sorted(m.runtimes.keys())) or "(none)"
            click.echo(f"{m.name}  v{m.version}  runtimes={runtimes_str}  ({f})")
        except manifest_mod.ManifestParseError as exc:
            click.echo(f"?  parse_error  ({f}): {exc}")


def _render_scaffold(
    name: str,
    description: str,
    author: str,
    license_id: str,
    runtime: str,
) -> str:
    runtimes_block = _render_runtimes(name, runtime)
    body = _render_body(name, runtime)
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        "version: 0.1.0\n"
        f"license: {license_id}\n"
        f"author: {author}\n"
        "agentskills_version: \"1.0\"\n"
        f"{runtimes_block}"
        "---\n"
        f"{body}"
    )


def _render_runtimes(name: str, runtime: str) -> str:
    lines = ["runtimes:"]
    if runtime in {"hermes", "both"}:
        lines.append("  hermes:")
        lines.append(f"    entrypoint: python -m clawhermes.skills.{name.replace('-', '_')}")
        lines.append("    capabilities: [memory.recall]")
    if runtime in {"openclaw", "both"}:
        lines.append("  openclaw:")
        lines.append(f"    entrypoint: node ./dist/{name.replace('-', '_')}.js")
        lines.append("    capabilities: [channels.send]")
    if runtime == "both":
        lines.append("  both:")
        lines.append("    requires_capabilities: [memory.recall]")
    return "\n".join(lines) + "\n"


def _render_body(name: str, runtime: str) -> str:
    return (
        f"# {name}\n\n"
        f"This skill was scaffolded by `claw-hermes skill new` for the `{runtime}` runtime "
        "configuration. Replace the description and the body below with a concrete account of "
        "what the skill does, when an agent should invoke it, and what inputs it expects.\n\n"
        "## When to invoke this skill\n\n"
        "- When the user asks for a behavior that this skill specifically implements.\n"
        "- Replace these bullets with the actual trigger phrases your skill listens for.\n\n"
        "## Inputs and outputs\n\n"
        "Document the parameters this skill accepts and the side effects or return values it "
        "produces. Keep the runtime entrypoint above in sync with the executable file that backs "
        "this manifest.\n"
    )
